---
title: "R code"
author: "nisrin"
date: "2024-02-20"
output: html_document
---
## setting up my environment by loading tidyverse backeges 
library(tidyverse)  #helps wrangle data
# Use the conflicted package to manage conflicts
library(conflicted)

# Set dplyr::filter and dplyr::lag as the default choices
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")

# STEP 1: COLLECT DATA

## Upload Divvy datasets (csv files) here

q1_2020 <- read_csv("Divvy_Trips_2020_Q1.csv")

q1_2020 <- read_csv("

q1_2020 <- read_csv

q1_2020 <- read_csv

q1_2020 <- read_csv

q1_2020 <- read_csv

q1_2020 <- read_csv

q1_2020 <- read_csv

q1_2020 <- read_csv



# STEP 2: WRANGLE DATA 


# Inspect the dataframes and look for incongruencies
## str(q1_2019)

# Convert ride_id and rideable_type to character so that they can stack correctly
q1_2020 <-  mutate(q1_2020, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type)) 


# Remove lat, long,  fields as this data was dropped beginning in 2020
all_trips <- all_trips %>%  
  select(-c(start_lat, start_lng, end_lat, end_lng))


# STEP 3: CLEAN UP AND ADD DATA TO PREPARE FOR ANALYSIS

# Inspect the new table that has been created
colnames(all_trips) 
nrow(all_trips) 
str(all_trips)  
 #Statistical summary of data. Mainly for numerics
summary(all_trips) 

# There are a few problems we will need to fix:

# (1) The data can only be aggregated at the ride-level, which is too granular. We will want to add some additional columns of data -- such as day, month, year -- that provide additional opportunities to aggregate the data.

# Add columns that list the date, month, day, and year of each ride
# This will allow us to aggregate ride data for each month, day, or year ...

q1_2020$date <- as.Date(all_trips$started_at) #The default format is yyyy-mm-dd
q1_2020$month <- format(as.Date(q1_2020$date), "%m")
q1_2020$day <- format(as.Date(q1_2020$date), "%d")
q1_2020$year <- format(as.Date(q1_2020$date), "%Y")
q1_2020$day_of_week <- format(as.Date(q1_2020$date), "%A")

# (2) We will want to add a calculated field for length of ride since the 2020Q1 data did not have the "tripduration" column. We will add "ride_length" to the entire dataframe for consistency.

# Add a "ride_length" calculation to q1_2020 (in seconds)

q1_2020$ride_length <- difftime(q1_2020$ended_at,q1_2020$started_at)

# Inspect the structure of the columns
str(q1_2020)

# Convert "ride_length" from Factor to numeric so we can run calculations on the data

is.factor(q1_2020$ride_length)
q1_2020$ride_length <- as.numeric(as.character(q1_2020$ride_length))
is.numeric(q1_2020$ride_length)

# (3) There are some rides where tripduration shows up as negative, including several hundred rides where Divvy took bikes out of circulation for Quality Control reasons. We will want to delete these rides.
# Remove "bad" data
# The dataframe includes a few hundred entries when bikes were taken out of docks and checked for quality by Divvy or ride_length was negative
# We will create a new version of the dataframe (v2) since data is being removed

q2_2020 <- q1_2020[!(q1_2020$start_station_name == "HQ QR" | q1+2020$ride_length<0),]


# STEP 4: CONDUCT DESCRIPTIVE ANALYSIS

# Descriptive analysis on ride_length (**all figures in seconds**)

summary(all_trips_v2$ride_length)

# Compare members and casual users
aggregate(q2_2020$ride_length ~ q2_2020$member_casual, FUN = mean)
aggregate(q2_2020$ride_length ~ q2_2020$member_casual, FUN = median)
aggregate(q2_2020$ride_length ~ q2_2020$member_casual, FUN = max)
aggregate(q2_2020$ride_length ~ q2_2020$member_casual, FUN = min)

# See the average ride time by each day for members vs casual users
aggregate(q2_2020$ride_length ~ q2_2020$member_casual + q2_2020$day_of_week, FUN = mean)

# Notice that the days of the week are out of order. Let's fix that.
q2_2020$day_of_week <- ordered(q2_2020$day_of_week, levels=c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))

# Now, let's run the average ride time by each day for members vs casual users
aggregate(q2_2020$ride_length ~ q2_2020$member_casual + q2_2020$day_of_week, FUN = mean)

# analyze ridership data by type and weekday
q2_2020 %>% 
  mutate(weekday = wday(started_at, label = TRUE)) %>%  #creates weekday field using wday()
  group_by(member_casual, weekday) %>%  #groups by usertype and weekday
  summarise(number_of_rides = n()							#calculates the number of rides and average duration 
            ,average_duration = mean(ride_length)) %>% 		# calculates the average duration
  arrange(member_casual, weekday)								# sorts

 mean(ride_length)) %>% 
  arrange(member_casual, weekday)  %>% 
  ggplot(aes(x = weekday, y = average_duration, fill = member_casual)) +
  geom_col(position = "dodge")


